### ISSUE TITLE
different eigen vectors in R and Python routines

### ISSUE THREAD

**Issue by alejandro-ariza** [EPauthenet/fda_oce_python#1]
Hi Etienne,

I noticed a different behavior in the R and Python eigen functions, `base::eigen` and `numpy.linalg.eig`. This yields to different vector matrices in your [R](https://github.com/EPauthenet/fda.oce/blob/38304dac0cf233c1cae1719c492365a72644acb0/R/fpca.R#L67) and [Python](https://github.com/EPauthenet/fda_oce_python/blob/20d92354581d5fb6975d40f4e4d4cf8f6c01359d/fda_oce_python.py#L101) fPCA routines.  

Matrices signs are different, below a simple example:

```
# R
> library(base)
> a = base::array(c(c(1,2,1), c(2,1,2), c(1,2,1)), dim=c(3,3))
> a
     [,1] [,2] [,3]
[1,]    1    2    1
[2,]    2    1    2
[3,]    1    2    1
> base::eigen(a)$vectors
          [,1]          [,2]       [,3]
[1,] 0.5417743  7.071068e-01  0.4544013
[2,] 0.6426206 -2.775558e-16 -0.7661846
[3,] 0.5417743 -7.071068e-01  0.4544013

# Python
>>> import numpy as np
>>> a = np.array([[1,2,1], [2,1,2], [1,2,1]])
>>> a
array([[1, 2, 1],
       [2, 1, 2],
       [1, 2, 1]])
>>> np.linalg.eig(a)[1]
array([[-5.41774320e-01, -7.07106781e-01,  4.54401349e-01],
       [-6.42620551e-01,  2.34720234e-18, -7.66184591e-01],
       [-5.41774320e-01,  7.07106781e-01,  4.54401349e-01]])
```

As you see, absolute numbers are identical, but signs are randomly different. This results in the following different matrices between your R and Python routines:
```
pca$vecnotWM != pca['vecnotWM'] 
pca$vectors  != pca['vectors' ] 
pca$axe      != pca['axes'    ]
```
I'm not sure whether this is relevant for the subsequent calculations, such as the principal components perturbation on the mean profile, classification, etc., but  I'm bringing this up just in case it's something to be fixed.

What you reckon?

**Comment by EPauthenet** [comment]
Hi Alejandro,

yes the result of the PCA is invariant by its sign, so it can happen that the sign of the eigenvector change if you slightly change the data. 
I guess in your case, R and Python must have different number of digits after the comma and so it reversed the first two vectors...
You can add a minus to have your eigenvector and PC in the direction you prefer for your results.

Cheers!
Etienne

**Comment by alejandro-ariza** [comment]
Thanks for your reply Etienne,

I run the eigen operations with the same decimal points in both the R and Python input matrices. So it's not yet clear to me why the different signs between `base::eigen` and `numpy.linalg.eig`. 

I see that the resulting principal components are the same, when running your R and Python routines. I was just wondering how the other matrices, which have different signs, might affect to subsequent operations. For instance, `pca$vector` is used to reconstruct the profiles with a chosen number of principal components in [here](https://github.com/EPauthenet/fda.oce/blob/38304dac0cf233c1cae1719c492365a72644acb0/R/reco.R).  The resulting functional data object will contain different coefficients. Do you think that's irrelevant for the reconstructed profile? Sorry if I'm missing something obvious!

**Comment by EPauthenet** [comment]
Ah then I don't know why it is reversed between R and Python, there must be something in the computation approximation.
No it is not a problem because the eigenvector is multiplied by their respective PC to reconstruct the profiles, 
`pca$vectors[d,1:Ntrunc] %*% t(pc[,1:Ntrunc])`
and the sign of the PCs is changed if the associated eigenvector is changed. You can check but the two first PCs in R and in Python should be of opposite sign too.

**Comment by alejandro-ariza** [comment]
That's it! You are right, any vector column with the sign changed corresponds with the same PC column with the sign changed too (when comparing results between `base::eigen` and `numpy.linalg.eig`). So the different performance between `base::eigen` and `numpy.linalg.eig`, whatever the reason is,  is NOT leading to differences between fda.oce and fda_oce_python. False alarm then ;)

Sorry about that, I just wanted to be sure that everything was right in the fda.oce Python side.

Thanks for your help!

**Comment by EPauthenet** [comment]
No problem, thanks for your vigilance!
